site_name: VaultKeeper
site_description: VaultKeeper documentation for PMVS course submission
theme:
  name: material
  language: en
  palette:
    primary: green
    accent: deep orange
nav:
  - Home: index.md
  - Functional Requirements: requirements.md
  - File Diagram: file-diagram.md
  - Additional Specification: specification.md
  - Database Schema: database.md
  - Presentation: presentation.md
